### PR TITLE
Fixing errors raised by g++ 4.7

### PR DESCRIPTION
**Pull request by rolanddenis**
# PR Description

Fixing following errors and warnings raised only by `g++ 4.7` ( 4.7.2 and 4.7.4 ):
- error with message `undefined reference to DGtal::KhalimskySpaceND<3u, int>::NEG` (same for `POS` and for `KhalimskyPreSpaceND`), see #1200. It is probably a bug of `g++` since there is no reason that he needs to take a reference to those static members (and there is no such errors with other compilers). However, adding a definition to those static members in namespace scope is a good thing since it will allow such usage if needed.
- ~~warning about unused parameter in defaulted constructors and assignment operators of `Khalimsky(Pre)SpaceND`. Don't know why he complains since it is only a definition but it's right that the parameter is useless here.~~ Eventually, I prefer to keep a proper documentation instead of clean compilation with `g++ 4.7`.
- error while constructing a `std::array` with initializer-list. A bug fixed in 4.8.0 : https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53361 .
- error with type aliasing, like in the following snippet:
```C++
using Image = ImageContainerBySTLVector<TDomain, TValue>;
using Value = typename Image::Value;
```
where it complains about not finding `Value` in `Image`. An another bug fixed in 4.8 : http://stackoverflow.com/questions/18213638/g-4-7-2-treatment-of-using-for-type-aliasing-seems-to-be-broken

It now compiles fine with `g++ 4.7.2` (on Debian Wheezy) and `g++ 4.7.4` (on Ubuntu 15.10) but the `C++11` support of 4.7.x versions is very buggy.

In addition, compilation with 4.8.5, 4.9.4, 5.2.1 on Ubuntu 15.10, and with 5.4.0 on Ubuntu 16.04 is done without warnings and errors with FFTW3, EIGEN (with #1197 applied), GMP, HDF5, OPENMP and QGLVIEWER options.

# Checklist

- ~~[ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).~~
- ~~[ ] Doxygen documentation of the code completed (classes, methods, types, members...)~~
- ~~[ ] Documentation module page added or updated.~~
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by kerautret** [comment]
Nice, I will have a look when you think that ready

**Comment by kerautret** [comment]
thank a lot!

**Comment by rolanddenis** [comment]
It is ready but as you may have see, I have reverted the commit about the warnings on "unused parameters". It should compile fine with `g++ 4.7` but with warnings on every `Khalimsky(Pre)SpaceND` usage (or every class that uses the same syntax).

I will trigger again Travis since `clang` segfault during compilation but I think you can already take a look :wink:.

**Comment by dcoeurjo** [comment]
Thanks a lot. Merging.
