### ISSUE TITLE
Master won't compile with clang 3.1.0 under macosx (xcode 4.3.2)

### ISSUE THREAD

**Issue by mtola** [DGtal-team/DGtal#655]
[  8%] Built target DGtal
[  9%] Building CXX object src/CMakeFiles/DGtalIO.dir/DGtal/io/boards/Board2D.cpp.o
In file included from /Users/noname/Desktop/DGtal/src/DGtal/io/boards/Board2D.cpp:30:
In file included from /Users/noname/Desktop/DGtal/src/DGtal/io/boards/Board2D.h:429:
In file included from /Users/noname/Desktop/DGtal/src/DGtal/io/Display2DFactory.h:47:
In file included from /Users/noname/Desktop/DGtal/src/DGtal/geometry/curves/ArithmeticalDSS.h:53:
In file included from /Users/noname/Desktop/DGtal/src/DGtal/base/ReverseIterator.h:45:
/Users/noname/Desktop/DGtal/src/DGtal/base/IteratorCirculatorTraits.h:180:55: error: non-type template argument of type 'bool' is not an integral constant expression
  typedef typename detail::IteratorCirculatorTypeImpl<IsCirculator<IC>::value >::Type Type; 
                                                      ^~~~~~~~~~~~~~~~~~~~~~~
/Users/noname/Desktop/DGtal/src/DGtal/base/IteratorCirculatorTraits.h:265:20: note: in instantiation of template class 'DGtal::IteratorCirculatorType<__gnu_cxx::__normal_iterator<const char *, std::basic_string<char> > >' requested here
  typedef typename IteratorCirculatorType<IC>::Type
                   ^
/Users/noname/Desktop/DGtal/src/DGtal/geometry/curves/FreemanChain.h:454:22: note: in instantiation of template class 'DGtal::IteratorCirculatorTraits<__gnu_cxx::__normal_iterator<const char *, std::basic_string<char> > >' requested here
    typedef typename IteratorCirculatorTraits<ConstIterator>::Value Value; 
                     ^
In file included from /Users/noname/Desktop/DGtal/src/DGtal/io/boards/Board2D.cpp:30:
In file included from /Users/noname/Desktop/DGtal/src/DGtal/io/boards/Board2D.h:429:
In file included from /Users/noname/Desktop/DGtal/src/DGtal/io/Display2DFactory.h:47:
In file included from /Users/noname/Desktop/DGtal/src/DGtal/geometry/curves/ArithmeticalDSS.h:56:
In file included from /Users/noname/Desktop/DGtal/src/DGtal/geometry/curves/SegmentComputerUtils.h:45:
/Users/noname/Desktop/DGtal/src/DGtal/base/Circulator.h:88:5: error: implicit instantiation of undefined template 'boost::STATIC_ASSERTION_FAILURE<false>'
    BOOST_STATIC_ASSERT(( boost::is_same< 
    ^
/usr/local/include/boost/static_assert.hpp:124:7: note: expanded from macro 'BOOST_STATIC_ASSERT'
      sizeof(::boost::STATIC_ASSERTION_FAILURE< BOOST_STATIC_ASSERT_BOOL_CAST( B ) >)>\
      ^
/Users/noname/Desktop/DGtal/src/DGtal/geometry/curves/FreemanChain.h:517:19: note: in instantiation of template class 'DGtal::Circulator<__gnu_cxx::__normal_iterator<const char *, std::basic_string<char> > >' requested here
  ConstCirculator c() const {
                  ^
/usr/local/include/boost/static_assert.hpp:54:26: note: template is declared here
template <bool x> struct STATIC_ASSERTION_FAILURE;
                         ^
2 errors generated.
make[2]: **\* [src/CMakeFiles/DGtalIO.dir/DGtal/io/boards/Board2D.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/DGtalIO.dir/all] Error 2
make: **\* [all] Error 2
